### ISSUE TITLE
Some `__str__` methods of nodes raise errors and warnings

### ISSUE THREAD

**Issue by jacobtylerwalls** [pylint-dev/astroid#1881] opened 2022-11-20 22:25 UTC
### Steps to reproduce
```python
>>> fd = astroid.nodes.FunctionDef()
>>> str(fd)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jacobwalls/astroid/astroid/nodes/node_ng.py", line 219, in __str__
    value = getattr(self, field)
            ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'FunctionDef' object has no attribute 'args'
```

Less severely, but still not great, launching python with warnings e.g. `python -Wall`:
```python
>>> cd = astroid.nodes.ClassDef()
>>> str(cd)
/Users/.../astroid/astroid/nodes/scoped_nodes/scoped_nodes.py:2041: DeprecationWarning: The 'ClassDef.doc' attribute is deprecated, use 'ClassDef.doc_node' instead.
```

***
We should add a unittest that generates the `str()` and `repr()` of all node types.

### `python -c "from astroid import __pkginfo__; print(__pkginfo__.version)"` output
2.12.13

**Comment by DanielNoord** [comment] 2022-11-20 22:26
The first issue is caused by the fact that the `str` relies on `postinit` being called I think.

I ran into this while debugging `astroid` many times..

**Comment by crazybolillo** [comment] 2023-06-06 20:19
I made a quick unit test on #2198. Am I going in the right direction? Also, I guess fixing the errors themselves will be part of this issue right?

**Comment by DanielNoord** [comment] 2023-06-06 20:30
I'd prefer using `pytest` semantics instead of `unittests` but that's more a review comment.

I think the bigger issue is that the reliance on `__postinit__` makes this very hard to solve. We would need to revisit either 1) what we put in the `__str__` or 2) how we instantiate nodes. Both are not optimal I think.

**Comment by jacobtylerwalls** [comment] 2023-06-06 20:32
I labeled this as a good first issue because I was hoping it wasn't requiring knowledge of any of that, just placing a good blank placeholder in the str/repr when the info is not available.

**Comment by DanielNoord** [comment] 2023-06-06 20:35
That would require a fix here:
https://github.com/pylint-dev/astroid/blob/a6eb2b87c5bfa39929b8047010788afce48461bf/astroid/nodes/node_ng.py#L213

I guess that would work? We don't really need a regression test for it though (I think).

**Closed** 2023-06-12 21:23 UTC
Labels: Bug 🪳, Good first issue
