### ISSUE TITLE
3.2.4 test failure

### ISSUE THREAD

**Issue by limburgher** [pylint-dev/astroid#2479] opened 2024-07-22 15:57 UTC
=================================== FAILURES ===================================
___________________ NonRegressionTests.test_numpy_distutils ____________________

self = <tests.test_regrtest.NonRegressionTests testMethod=test_numpy_distutils>

        @unittest.skipUnless(HAS_NUMPY, "Needs numpy")
        def test_numpy_distutils(self):
            """Special handling of virtualenv's patching of distutils shouldn't interfere
            with numpy.distutils.
    
            PY312_PLUS -- This test will likely become unnecessary when Python 3.12 is
            numpy's minimum version. (numpy.distutils will be removed then.)
            """
            node = extract_node(
                """
    from numpy.distutils.misc_util import is_sequence
    is_sequence("ABC") #@
    """
            )
            inferred = node.inferred()
>           self.assertIsInstance(inferred[0], nodes.Const)
E           AssertionError: Uninferable is not an instance of <class 'astroid.nodes.node_classes.Const'>

tests/test_regrtest.py:118: AssertionError
=========================== short test summary info ============================
FAILED tests/test_regrtest.py::NonRegressionTests::test_numpy_distutils - Ass...
= 1 failed, 1629 passed, 40 skipped, 7 deselected, 16 xfailed in 69.16s (0:01:09) =

This is on Fedora, fails on Python 3.12 and 3.13.

**Comment by jacobtylerwalls** [comment] 2024-07-24 03:31
Thanks for the report, AFAICT this is a duplicate of #2442

**Comment by jacobtylerwalls** [comment] 2024-07-24 03:38
Never mind! Just reproduce with numpy==1.26.4

**Closed** 2024-07-24 11:40 UTC

**Comment by limburgher** [comment] 2024-07-24 13:47
Thank you!
