### ISSUE TITLE
Missing node ancestors

### ISSUE THREAD

**Issue by epenet** [pylint-dev/astroid#2631] opened 2024-10-30 10:04 UTC
Hi :wave:

I've bumped into an issue in a pylint plugin at Home Assistant, where requesting ancestors from a node fails to retrieve the full list of ancestors.

I have a class defined as 
```python
class DevoloScannerEntity(
    CoordinatorEntity[DevoloDataUpdateCoordinator[list[ConnectedStationInfo]]],
    ScannerEntity,
):
```

I am analysing the node ancestors using `ancestors = list(node.ancestors())` and some are missing!
I would expect all ancestors to be: `['CoordinatorEntity', 'BaseCoordinatorEntity', 'Entity', 'object', 'ScannerEntity', 'BaseTrackerEntity']`
But the display shows: `['CoordinatorEntity', 'BaseCoordinatorEntity', 'Entity', 'object']`
It is missing `ScannerEntity` and `BaseTrackerEntity`

See sample run on https://github.com/home-assistant/core/actions/runs/11589842191/job/32266212034?pr=129483

I am unsure if it is linked to https://github.com/pylint-dev/pylint/issues/9138 or not.
I may be linked to the version of Python (I am unable to reproduce locally with python 3.12.3 - the CI is running python 3.12.7)
There are three instances of `ValueError: generator already executing`

```console
Python 3.12.7
Exception ignored in: <generator object raise_if_nothing_inferred.<locals>.inner at 0x7f2f6ba5ae40>
Traceback (most recent call last):
  File "/home/runner/work/core/core/venv/lib/python3.12/site-packages/astroid/decorators.py", line 99, in inner
    yield from generator
ValueError: generator already executing
Exception ignored in: <generator object raise_if_nothing_inferred.<locals>.inner at 0x7f2f683ec340>
Traceback (most recent call last):
  File "/home/runner/work/core/core/venv/lib/python3.12/site-packages/astroid/decorators.py", line 99, in inner
    yield from generator
ValueError: generator already executing
Exception ignored in: <generator object raise_if_nothing_inferred.<locals>.inner at 0x7f2f06355840>
Traceback (most recent call last):
  File "/home/runner/work/core/core/venv/lib/python3.12/site-packages/astroid/decorators.py", line 99, in inner
    yield from generator
ValueError: generator already executing
...
All ancestors for homeassistant.components.devolo_home_network.device_tracker.DevoloScannerEntity: ['CoordinatorEntity', 'BaseCoordinatorEntity', 'Entity', 'object']
...
************* Module homeassistant.components.devolo_home_network.device_tracker
Warning: homeassistant/components/devolo_home_network/device_tracker.py:84:0: C7461: Derived CoordinatorEntity is recommended to be placed in the 'entity' module (hass-enforce-class-module)
...
Error: Process completed with exit code 16.
```

**Comment by epenet** [comment] 2024-10-30 10:06
Note: it seems to be at least partly related to parallelism - as running pylint with `jobs=1` makes the issue go away.
https://github.com/home-assistant/core/actions/runs/11590052863/job/32266876576
That gets rid of two `ValueError: generator already executing`, and causes the ancestors to be correctly retrieved

**Comment by DanielNoord** [comment] 2024-10-30 21:00
Isn't this a duplicate of https://github.com/pylint-dev/pylint/issues/9138?

**Comment by epenet** [comment] 2024-10-30 21:06
> Isn't this a duplicate of [pylint-dev/pylint#9138](https://github.com/pylint-dev/pylint/issues/9138)?

As I said in the description... I am not sure!
It might be the same root cause but it also kinda feels different.

**Comment by DanielNoord** [comment] 2024-10-30 21:08
Oh I'm sorry, completely overlooked that.

But yeah, I think it is very likely the same. Especially since the version and repository match. Closing this as duplicate (for now)

**Closed by DanielNoord** 2024-10-30 21:08 UTC
